#define WINDFARM_EI 3
#define WINDFARM_COST 10
#define WINDFARM_CAPACITY 10
#define WINDFARM_MAXIMUM 5

#define HYDROPLANT_EI 10
#define HYDROPLANT_COST 100
#define HYDROPLANT_CAPACITY 60
#define HYDROPLANT_MAXIMUM 2

#define SOLARPOWER_EI 2
#define SOLARPOWER_COST 30
#define SOLARPOWER_CAPACITY 10
#define SOLARPOWER_MAXIMUM 3

#define COAL_EI 50
#define COAL_COST 50
#define COAL_CAPACITY 50

#define NUCLEAR_EI 20
#define NUCLEAR_COST 100
#define NUCLEAR_CAPACITY 100
